mode: train
data: gamuda_weld.yaml
model: yolo11n.pt

hsv_h: 0.03        # hue
hsv_s: 0.6         # saturation
hsv_v: 0.5         # value (brightness)
fliplr: 0.5        # horizontal flip probability
flipud: 0.1        # vertical flip probability
translate: 0.1     # image translation fraction
scale: 0.5         # scale factor
shear: 0.0         # shear angle
perspective: 0.0   # perspective distortion
mosaic: 1.0        # mosaic probability
mixup: 0.0         # mixup probability
erasing: 0.4       # random erasing
